# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prueba_interfaz1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
import threading
import sqlite3
import time

class Ui_Interfaz(object):
	def setupUi(self, Interfaz):
		
		#Variables interfaz
		serialPort1 = 'COM8' # Debe revisarse el puerto al que se conecta el GINS
		serialPort2 = 'COM9' # Debe revisarse el puerto al que se conecta el GINS
		baudRate1 = 9600

		print('Inicio')
		## GINS200=serial('COM5','BaudRate',460800,'Parity','none','DataBits',8,'StopBits',1,'Terminator','CR')
		self.mSerial1=MSerialPort(serialPort1,baudRate1)#, parity='PARITY_NONE', bytesize='EIGHTBITS', stopbits='STOPBITS_ONE')
		self.mSerial2=MSerialPort(serialPort2,baudRate1)#, parity='PARITY_NONE', bytesize='EIGHTBITS', stopbits='STOPBITS_ONE')
		
		Interfaz.setObjectName("Interfaz")
		Interfaz.resize(400, 300)
		self.buttonBox = QtWidgets.QDialogButtonBox(Interfaz)
		self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName("buttonBox")
		self.horizontalLayoutWidget = QtWidgets.QWidget(Interfaz)
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 221))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout()
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.horizontalLayout_9.addWidget(self.label)
		self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_2.setFont(font)
		self.label_2.setFrameShape(QtWidgets.QFrame.Box)
		self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.label_2.setObjectName("label_2")
		self.horizontalLayout_9.addWidget(self.label_2)
		self.verticalLayout_3.addLayout(self.horizontalLayout_9)
		self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.horizontalLayout_8.addWidget(self.label_4)
		self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_3.setFont(font)
		self.label_3.setFrameShape(QtWidgets.QFrame.Box)
		self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.label_3.setObjectName("label_3")
		self.horizontalLayout_8.addWidget(self.label_3)
		self.verticalLayout_3.addLayout(self.horizontalLayout_8)
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.label_6.setFont(font)
		self.label_6.setObjectName("label_6")
		self.horizontalLayout_7.addWidget(self.label_6)
		self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_5.setFont(font)
		self.label_5.setFrameShape(QtWidgets.QFrame.Box)
		self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.label_5.setObjectName("label_5")
		self.horizontalLayout_7.addWidget(self.label_5)
		self.verticalLayout_3.addLayout(self.horizontalLayout_7)
		self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.label_8.setFont(font)
		self.label_8.setObjectName("label_8")
		self.horizontalLayout_6.addWidget(self.label_8)
		self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_7.setFont(font)
		self.label_7.setFrameShape(QtWidgets.QFrame.Box)
		self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.label_7.setObjectName("label_7")
		self.horizontalLayout_6.addWidget(self.label_7)
		self.verticalLayout_3.addLayout(self.horizontalLayout_6)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.label_10.setFont(font)
		self.label_10.setObjectName("label_10")
		self.horizontalLayout_5.addWidget(self.label_10)
		self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_9.setFont(font)
		self.label_9.setFrameShape(QtWidgets.QFrame.Box)
		self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.label_9.setObjectName("label_9")
		self.horizontalLayout_5.addWidget(self.label_9)
		self.verticalLayout_3.addLayout(self.horizontalLayout_5)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.label_12.setFont(font)
		self.label_12.setObjectName("label_12")
		self.horizontalLayout_2.addWidget(self.label_12)
		self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_11.setFont(font)
		self.label_11.setFrameShape(QtWidgets.QFrame.Box)
		self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.label_11.setObjectName("label_11")
		self.horizontalLayout_2.addWidget(self.label_11)
		self.verticalLayout_3.addLayout(self.horizontalLayout_2)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.label_14.setFont(font)
		self.label_14.setObjectName("label_14")
		self.horizontalLayout_3.addWidget(self.label_14)
		self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_13.setFont(font)
		self.label_13.setFrameShape(QtWidgets.QFrame.Box)
		self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.label_13.setObjectName("label_13")
		self.horizontalLayout_3.addWidget(self.label_13)
		self.verticalLayout_3.addLayout(self.horizontalLayout_3)
		self.horizontalLayout.addLayout(self.verticalLayout_3)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout.addLayout(self.verticalLayout)
		self.pushButton = QtWidgets.QPushButton(Interfaz)
		self.pushButton.setGeometry(QtCore.QRect(10, 240, 75, 23))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.pushButton.setFont(font)
		self.pushButton.setObjectName("pushButton")
		self.pushButton.clicked.connect(self.start_aqcuisition)
		self.retranslateUi(Interfaz)
		self.buttonBox.accepted.connect(Interfaz.accept) # type: ignore
		self.buttonBox.rejected.connect(Interfaz.reject) # type: ignore
		QtCore.QMetaObject.connectSlotsByName(Interfaz)

	def retranslateUi(self, Interfaz):
		_translate = QtCore.QCoreApplication.translate
		Interfaz.setWindowTitle(_translate("Interfaz", "Dialog"))
		self.label.setText(_translate("Interfaz", "v1"))
		self.label_2.setText(_translate("Interfaz", "TextLabel"))
		self.label_4.setText(_translate("Interfaz", "v2"))
		self.label_3.setText(_translate("Interfaz", "TextLabel"))
		self.label_6.setText(_translate("Interfaz", "v3"))
		self.label_5.setText(_translate("Interfaz", "TextLabel"))
		self.label_8.setText(_translate("Interfaz", "v4"))
		self.label_7.setText(_translate("Interfaz", "TextLabel"))
		self.label_10.setText(_translate("Interfaz", "v5"))
		self.label_9.setText(_translate("Interfaz", "TextLabel"))
		self.label_12.setText(_translate("Interfaz", "v6"))
		self.label_11.setText(_translate("Interfaz", "TextLabel"))
		self.label_14.setText(_translate("Interfaz", "v7"))
		self.label_13.setText(_translate("Interfaz", "TextLabel"))
		self.pushButton.setText(_translate("Interfaz", "Iniciar"))

	def setValues(self):
		self.label_2.setText("Texto v1")
		self.label_3.setText("Texto v2")
		self.label_5.setText("Texto v3")
		self.label_7.setText("Texto v4")
		self.label_9.setText("Texto v5")
		self.label_11.setText("Texto v6")
		self.label_13.setText("Texto v7")

	def start_aqcuisition(self):
		self.t1 = threading.Thread(target = self.mSerial1.read_data)
		self.t1.start()
		self.t2 = threading.Thread(target = self.mSerial2.read_data)
		self.t2.start()
		self.t3 = threading.Thread(target = self.get_values)
		self.t3.start()

	def get_values(self):
		db_Name = "pruebaDB_COM.db"
		db_Table = "Variables_USB"
		self.db1 = Database(db_Name,db_Table)
		print('DB Conectada')

		for i in range(0,10):
			time.sleep(1)
			self.data1 = self.mSerial1.message
			print(f'Dato 1: {self.data1}')
			self.data1 = self.data1.replace("[","").replace("]","").replace("\r\n","")
			self.data1 = list(map(float, self.data1.split(",")))
			
			self.data2 = self.mSerial2.message
			print(f'Dato 2: {self.data2}')
			self.data2 = self.data2.replace("[","").replace("]","").replace("\r\n","")
			self.data2 = list(map(float, self.data2.split(",")))

			self.label_2.setText(str(i+self.data1[0]))
			self.label_3.setText(str(i+self.data1[1]))
			self.label_5.setText(str(i+self.data1[2]))
			self.label_7.setText(str(i+self.data2[0]))
			self.label_9.setText(str(i+self.data2[1]))
			self.label_11.setText(str(i+self.data2[2]))
			self.label_13.setText(str(i+self.data2[3]))

			print(self.data1+self.data2)
			self.db1.save_data(self.data1+self.data2)
			print('---------------------------')
		
		self.mSerial1.read_flag = True
		self.mSerial1.port_close()
		self.mSerial2.read_flag = True
		self.mSerial2.port_close()
		print('Puertos cerrados!')
		self.t1.join()
		self.t2.join()
		print('Hilos finalizados!')
		#self.t3.join()

class Database:
	db_conn = None
	db_flag = False #Aún sin uso
	def __init__(self,db_name,db_table):
		try:
			self.db_name = db_name
			self.db_table = db_table
			self.db_conn = sqlite3.connect("database/" + db_name)
			self.cursor = self.db_conn.cursor()
			
		except Exception as ex:
			print(ex)
	def save_data(self,data):
		try:
			self.cursor.execute("CREATE TABLE IF NOT EXISTS " + self.db_table + " (n REAL , v1 REAL NOT NULL, v2 REAL NOT NULL, v3 REAL NOT NULL, v4 REAL NOT NULL, v5 REAL NOT NULL,v6 REAL NOT NULL, v7 REAL NOT NULL, PRIMARY KEY (n))")
			self.cursor.execute("INSERT INTO " + self.db_table + "(v1,v2,v3,v4,v5,v6,v7) VALUES(?,?,?,?,?,?,?)",tuple(data))
			self.db_conn.commit()
		except Exception as ex:
			print(ex)
	def conn_close(self):
		self.db_conn.close()


class MSerialPort:
	message=''
	read_flag = False
	def __init__(self,port,baud):
		self.port=serial.Serial(port,baud)
		if not self.port.isOpen():
			self.port.open()
	def port_open(self):
		if not self.port.isOpen():
			self.port.open()
	def port_close(self):
		self.port.close()
	def send_data(self,data):
		number=self.port.write(data)
		return number
	def read_data(self):
		while True:
			data=self.port.readline()
			self.message=data.decode('ascii')
			if self.read_flag:
				self.read_flag = False
				break

if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	Interfaz = QtWidgets.QDialog()
	ui = Ui_Interfaz()
	ui.setupUi(Interfaz)
	Interfaz.show()
	sys.exit(app.exec_())
